name: Build and Deploy Spring Boot Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Docker image
        run: ./mvnw bootBuildImage

      - name: List Docker images
        run: docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag movie-ai-api:0.0.1-SNAPSHOT ghcr.io/${{ github.repository_owner }}/movie-ai-api:${{ github.sha }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/axon:${{ github.sha }}

      - name: Deploy to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://patrick@patrickdronk.dev:22/movie-ai-api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ghcr.io/${{ github.repository_owner }}/movie-ai-api:${{ github.sha }}